### ISSUE TITLE
Malformed configuration file

### ISSUE THREAD

**Issue by megrimm** [alombarte/raspberry-osmc-automated#3]
Hello,

Thanks for your script!

I followed your instructions and the the following error. Any thoughts?

osmc@osmc-rpi:~/TV Shows$ /usr/local/bin/flexget exec
2015-11-25 14:20 CRITICAL manager                       mapping values are not allowed here in "<unicode string>", line 14, column 55: ... s.info/rss.php?user_id=284950rss: http://showrss.info/rss.php?us ... ^

---
##  Malformed configuration file (check messages above). Common reasons:

 o Indentation error
 o Missing : from end of the line
 o Non ASCII characters (use UTF8)
 o If text contains any of :[]{}% characters it must be single-quoted (eg. value{1} should be 'value{1}')

 Reason: mapping values are not allowed here

 ----> MOST LIKELY REASON: Missing : from end of the line!

 Check configuration near line 13, column 54

 Fault is almost always in this or previous line

2015-11-25 14:20 CRITICAL manager                       Failed to load config file: Config file is not valid YAML
Could not start manager: Config file is not valid YAML

**Comment by alombarte** [comment]
Thank you for reporting @megrimm . Can you please verify if the URL you used contains the character `&`? I'll work in a fix for that. In the mean time you might want to edit manually the file `.raspberry-osmc-automated/flexget/config.yml` and correct the URL for your RSS. I believe this is the reason.

**Comment by alombarte** [comment]
Problem is fixed now, when an URL contained the symbol `&` the substitution was going wild (`&` is a special char in `sed` command).

To test the solution the install script should be executed again, although in your case it will be much cheaper if you just edit the file `.raspberry-osmc-automated/flexget/config.yml` and edit the line 14 to leave `rss: http://showrss.info/rss.php?user_id=284950` (important to respect the spaces for identation, don't use tabs)

**Comment by megrimm** [comment]
pulled 541e708 but still getting similar error?: i can keep running the script instead of editting .raspberry-osmc-automated/flexget/config.yml to nail the bugs if you want...

error: Couldn't find a setup script in /home/osmc/Scripts/raspberry-osmc-automated/flexget
2015-11-25 17:04 CRITICAL manager                       mapping values are not allowed here in "<unicode string>", line 14, column 55: ... s.info/rss.php?user_id=284950rss: http://showrss.info/rss.php?us ... ^

---

##  Malformed configuration file (check messages above). Common reasons:

 o Indentation error
 o Missing : from end of the line
 o Non ASCII characters (use UTF8)
 o If text contains any of :[]{}% characters it must be single-quoted (eg. value{1} should be 'value{1}')

 Reason: mapping values are not allowed here

 ----> MOST LIKELY REASON: Missing : from end of the line!

 Check configuration near line 13, column 54

 Fault is almost always in this or previous line

2015-11-25 17:04 CRITICAL manager                       Failed to load config file: Config file is not valid YAML
Could not start manager: Config file is not valid YAML

**Comment by megrimm** [comment]
hmmmmmm .... here is my line 14:

rss: http://showrss.info/rss.php?user_id=284950rss: http://showrss.info/rss.php?user_id=284950rss: http://showrss.info/rss.php?user_id=284950rss: Deleting default OSMC folders.hd=nullrss: http://sho...... continued for as many times i ran script

seems line 14 is not "replaced" when script is run more than once it is just "added" to?

**Comment by alombarte** [comment]
The placeholder variable `CONFIG_RSS_FEED` is replaced in the first execution of the script. There is no way that executing it more times will fix anything unless you restore the config.yml at its original state.
